# Generated by Django 3.2 on 2022-04-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authonticate', '0005_auto_20220416_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='BussinessPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=36, null=True, verbose_name='Name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authonticate.merchant', verbose_name='Merchant')),
            ],
            options={
                'verbose_name': 'Bussiness Plane ',
                'verbose_name_plural': 'Bussiness Planes ',
                'unique_together': {('name', 'merchant')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('editable_answers', models.BooleanField(default=True, verbose_name='Users can edit their answers')),
                ('display_method', models.SmallIntegerField(choices=[(1, 'By question'), (2, 'By category'), (0, 'All in one page')], default=0, verbose_name='Display method')),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text')),
                ('required', models.BooleanField(default=True, verbose_name='Required')),
                ('type', models.CharField(choices=[('text', 'text'), ('select', 'select')], default='text', max_length=200, verbose_name='Type')),
                ('choices', models.TextField(blank=True, help_text='This Field is required only when type is select', null=True, verbose_name='Choices')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Categorys', to='questionnaire.category', verbose_name='Category')),
                ('questionnaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='questionnaire.questionnaire', verbose_name='Questionnaire')),
            ],
            options={
                'verbose_name': 'question',
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_uuid', models.CharField(max_length=36, verbose_name='Response unique identifier')),
                ('bussiness_plane', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.bussinessplan')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='questionnaire.questionnaire', verbose_name='Questionnaire')),
            ],
            options={
                'verbose_name': 'Questionnaire Respone',
                'verbose_name_plural': 'Questionnaire Respones',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Update date')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.question', verbose_name='Question')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.qresponse', verbose_name='Response')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': 'Answers',
            },
        ),
    ]
