# Generated by Django 3.2 on 2022-04-17 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qresponse',
            name='response_uuid',
        ),
    ]
