# Generated by Django 3.2 on 2022-04-16 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='Active')),
                ('failed_attempts', models.IntegerField(default=0, verbose_name='Failed Attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_live', models.BooleanField(default=False, verbose_name='Live')),
                ('national_id', models.CharField(blank=True, max_length=16, null=True, verbose_name='National ID')),
                ('merchant_status', models.IntegerField(choices=[(0, 'Active'), (1, 'In_Progress')], default=1, help_text="This represents the merchant's account management status. ", verbose_name='Merchant Status')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='City')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='authonticate_merchant_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
                'unique_together': {('user', 'national_id')},
            },
        ),
    ]
