# Generated by Django 3.2 on 2022-04-16 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchant',
            options={},
        ),
        migrations.AddField(
            model_name='merchant',
            name='email',
            field=models.EmailField(default='test@123.c', max_length=255, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='password',
            field=models.CharField(default='Progmmg@1321', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='merchant',
            name='merchant_status',
            field=models.IntegerField(choices=[(0, 'in_progress'), (1, 'live')], default=0, help_text="This represents the merchant's onboarding status.", verbose_name='Merchant Status'),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Created at'),
        ),
        migrations.AlterUniqueTogether(
            name='merchant',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='active',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='city',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='failed_attempts',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='is_live',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='user',
        ),
    ]
