# Generated by Django 3.2 on 2022-04-16 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authonticate', '0002_auto_20220416_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='email',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='password',
        ),
        migrations.AddField(
            model_name='merchant',
            name='failed_attempts',
            field=models.IntegerField(default=0, verbose_name='Failed Attempts'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='authonticate_merchant_related', to='auth.user'),
            preserve_default=False,
        ),
    ]
