# Generated by Django 3.2 on 2022-04-16 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authonticate', '0003_auto_20220416_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='merchant',
            old_name='is_active',
            new_name='active_merchant',
        ),
    ]
