# Generated by Django 3.2 on 2022-04-16 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authonticate', '0004_rename_is_active_merchant_active_merchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='national_id',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='National ID'),
        ),
    ]
